-- Flyway Migration V1: Initial Table Schemas & Performance B-Tree Indexes (ANSI SQL Standard)

-- 1. Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Products Table
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    description TEXT,
    image_url VARCHAR(512),
    external_url VARCHAR(512),
    options VARCHAR(255),
    is_custom BOOLEAN DEFAULT FALSE,
    icon VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Curation Boxes Table
CREATE TABLE curation_boxes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    min_budget INT NOT NULL,
    max_budget INT NOT NULL,
    message_card TEXT,
    sharing_token VARCHAR(255) UNIQUE NOT NULL,
    allow_custom_input BOOLEAN DEFAULT TRUE,
    status VARCHAR(50) DEFAULT 'CREATED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expired_at TIMESTAMP
);

-- 4. Curation Box Items Table
CREATE TABLE curation_box_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curation_box_id BIGINT REFERENCES curation_boxes(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE
);

-- 5. Orders & Settlement Table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curation_box_id BIGINT REFERENCES curation_boxes(id),
    sender_id BIGINT REFERENCES users(id),
    receiver_id BIGINT REFERENCES users(id),
    selected_product_id BIGINT REFERENCES products(id),
    selected_option VARCHAR(255),
    payment_key VARCHAR(255),
    total_amount INT NOT NULL,
    final_amount INT,
    refund_amount INT DEFAULT 0,
    recipient_name VARCHAR(100),
    recipient_phone VARCHAR(20),
    shipping_address TEXT,
    shipping_status VARCHAR(50) DEFAULT 'PREPARING',
    carrier_name VARCHAR(100) DEFAULT 'CJ대한통운',
    tracking_number VARCHAR(100) DEFAULT '6849-3012-9381',
    paid_at TIMESTAMP,
    settled_at TIMESTAMP
);

-- 6. Performance B-Tree Indexes
CREATE INDEX idx_orders_sender_id ON orders(sender_id);
CREATE INDEX idx_orders_receiver_id ON orders(receiver_id);
CREATE INDEX idx_orders_recipient_phone ON orders(recipient_phone);
CREATE INDEX idx_curation_boxes_sharing_token ON curation_boxes(sharing_token);
