-- Flyway Migration V7: Create Support Inquiries Table
CREATE TABLE support_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_code VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    content TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'IN_PROGRESS',
    admin_reply TEXT,
    replied_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO support_inquiries (inquiry_code, name, email, category, content, status, admin_reply, replied_at, created_at)
VALUES 
('INQ-104921', '김하늘', 'sky.kim@example.com', '배송/일정 문의', '선물 수락 시 희망 배송일을 이번 주 토요일로 지정했는데, 혹시 일정을 하루 당겨서 금요일에 받을 수 있을지 문의드립니다.', 'ANSWERED', '안녕하세요 고객님, 담당 배송 기사님 및 물류센터와 확인하여 금요일 출고 및 수령 일정으로 조율 도와드렸습니다. 감사합니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('INQ-382910', '이지우', 'jiwoo.lee@example.com', '정산/환불 문의', '보낸 선물의 수령인이 제품을 선택하고 남은 차액 환불이 언제 입금되는지 알고 싶습니다.', 'ANSWERED', '안녕하세요 고객님, 수령인이 선물을 수락하는 즉시 PG사를 통해 차액 부분 환불이 자동 접수되며, 카드사 영업일 기준 2~3일 내에 한도 복원 또는 환불 처리됩니다.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('INQ-882103', '박서준', 'seojun.park@example.com', '선물 박스/메시지 문의', '선물 상자 개봉용 4자리 안심 PIN 번호를 잘못 입력해서 친구가 열람을 못하고 있습니다. 핀 번호 초기화 가능한가요?', 'IN_PROGRESS', NULL, NULL, CURRENT_TIMESTAMP);
